/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./tools/chrome-sandbox/renderer/components/ActionBar.vue')['default']
    AppSettingsDialog: typeof import('./renderer/shared/components/AppSettingsDialog.vue')['default']
    CreateDialog: typeof import('./tools/chrome-sandbox/renderer/components/CreateDialog.vue')['default']
    DataDirectoryField: typeof import('./tools/chrome-sandbox/renderer/components/DataDirectoryField.vue')['default']
    DataDirectorySetupDialog: typeof import('./tools/chrome-sandbox/renderer/components/DataDirectorySetupDialog.vue')['default']
    EditDialog: typeof import('./tools/chrome-sandbox/renderer/components/EditDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EnvDialog: typeof import('./tools/env-browser/renderer/components/EnvDialog.vue')['default']
    FingerprintEditor: typeof import('./tools/chrome-sandbox/renderer/components/FingerprintEditor.vue')['default']
    LaunchOptionsFields: typeof import('./tools/chrome-sandbox/renderer/components/LaunchOptionsFields.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandboxCard: typeof import('./tools/chrome-sandbox/renderer/components/SandboxCard.vue')['default']
    SettingsDialog: typeof import('./tools/chrome-sandbox/renderer/components/SettingsDialog.vue')['default']
    Sidebar: typeof import('./tools/chrome-sandbox/renderer/components/Sidebar.vue')['default']
    StatusPanel: typeof import('./tools/chrome-sandbox/renderer/components/StatusPanel.vue')['default']
    ToolCard: typeof import('./renderer/shared/components/ToolCard.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
