shellEmulator: true
trustPolicy: no-downgrade
packages:
  - .
  - '!data/**'
  - '!release/**'
  - '!dist/**'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
